module.exports = {
    data: 
    [
        {
            "uuid": "3a4c9858-4028-4218-8e9e-e36cc4111290",
            "company_name": "Abbott",
            "job_scraper": true,
            "createdAt": "2022-05-27T22:45:03.246Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://www.jobs.abbott/us/en/search-results?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com",
            "company_website": "https://www.jobs.abbott/us/en/",
            "industry": "Hospital & Healthcare",
            "imagelink": "https://ucarecdn.com/ec44459c-9002-4b40-a6bc-c556351ac4dd/abbott-logo-500x313.png",
            "company_summary": "Abbott's life-changing technology helps people live fully and offers information, medicines and breakthroughs to help you manage your health.",
            "company_description": "Abbott is a global healthcare leader that helps people live more fully at all stages of life. Our portfolio of life-changing technologies spans the spectrum of healthcare, with leading businesses and products in diagnostics, medical devices, nutritionals and branded generic medicines. Our 113,000 colleagues serve people in more than 160 countries.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "Abbott’s Freedom 2 Save (F2S) program addresses our belief that employees shouldn’t have to choose between paying off student loans and saving for retirement. Under the plan, employees who are currently repaying a student loan, and these payments equal at least two percent of their eligible pay, will receive a five percent company match deposited into their Abbott Stock Retirement Plan (SRP) account without having to make contributions to the SRP.\n\nIf you are enrolled in F2S and making your own contributions to the SRP, you will only receive the F2S matching contribution. All employees who are eligible to participate in the SRP are eligible to enroll in F2S on their first day of employment.",
            "link_to_benefit_details": "https://www.abbott.com/corpnewsroom/strategy-and-strength/company-student-loan-perk.html#:~:text=Abbott's%20Freedom%202%20Save%20program,pay%20off%20their%20loans%20faster."
        },
        {
            "uuid": "c7825ccd-8b9c-4186-b1bb-2fe2d7ba0a80",
            "company_name": "Aetna, A CVS Company",
            "job_scraper": true,
            "createdAt": "2022-05-27T22:45:03.246Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://jobs.cvshealth.com/?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com",
            "company_website": "https://www.aetna.com/",
            "industry": "Health, Wellness & Fitness",
            "imagelink": "https://ucarecdn.com/eb64dc40-81cb-4a02-9350-3dca3f665264/aetna-logo.png",
            "company_summary": "At Aetna, a CVS Health Company, we are building a healthier world by making healthcare easy, affordable and all about you.",
            "company_description": "Founded in 1853 in Hartford, CT, Aetna is one of the nation's leading diversified health care benefits companies, serving an estimated 46.7 million people with information and resources to help them make better decisions about their healthcare.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "Aetna will match employees U.S.-based student loan payments up to $2,000 per year for a lifetime maximum of up to $10,000 for qualifying loans. For part-time employees, Aetna will match up to $1,000 a year with a lifetime maximum of $5,000.",
            "link_to_benefit_details": "https://www.cvshealth.com/news-and-insights/press-releases/fact-sheet-aetna-program-to-help-thousands-of-employees-repay#:~:text=Aetna%20already%20offers%20a%20tuition,may%20benefit%20from%20both%20programs"
        },
        {
            "uuid": "79328a45-a348-463a-b73d-39b89adcfa46",
            "company_name": "AlloSource",
            "job_scraper": true,
            "createdAt": "2022-06-29T04:17:40.703Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://careers-allosource.icims.com/jobs/search?mobile=false&width=1038&height=500&bga=true&needsRedirect=false&jan1offset=-300&jun1offset=-240%3Futm_source%3Ddwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com",
            "company_website": "https://allosource.org/",
            "industry": "Medical Equipment Manufacturing",
            "imagelink": "https://ucarecdn.com/10aac936-034d-4f4d-b49a-d55fcbafe6a6/allosource-logo.png",
            "company_summary": "AlloSource is a healthcare company with a mission to help patients heal through innovative cellular and allograft research.",
            "company_description": "As one of the world's leading manufacturers of fresh cartilage tissue used for joint repair and skin allografts to heal severe burns, AlloSource has grown into one of the largest tissue networks in the country with more than 450 employees. \n  \n  With over 200 types of precise bone, skin, soft-tissue and custom-machined allografts, our organization offers products for an array of life-saving and life-enhancing medical procedures. We deliver unparalleled expertise and customer service to our growing network of surgeons, partners and the country's most reputable Organ Procurement Organizations.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "AlloSource partners with Tuition.io for their student loan reimbursement benefit.\n\nEach month, AlloSource will contribute a percentage to the principal balance of your student loan.",
            "link_to_benefit_details": "https://allosource.org/allosource-partners-with-tuition-io-to-help-employees-pay-down-student-debt/"
        },
        {
            "uuid": "b9dd326d-0dcc-461e-b557-00ba48744d87",
            "company_name": "Ally Financial",
            "job_scraper": true,
            "createdAt": "2022-06-29T04:17:40.703Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://ally.avature.net/careers?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com",
            "company_website": "https://www.ally.com/",
            "industry": "Financial Services",
            "imagelink": "https://ucarecdn.com/4ff3fa59-65c8-4b0a-a7cf-859171315359/ally-financial.png",
            "company_summary": "Ally Financial provides financial services including car finance, online banking via a direct bank, corporate lending, vehicle insurance, mortgage loans, and an an electronic trading platform to trade financial assets.",
            "company_description": "We're relentlessly focused on Doing it Right and being a trusted financial services provider to our consumer, commercial, and corporate customers. \n  \nWe are one of the largest full-service automotive finance operations in the country and offer a wide range of financial services and insurance products to automotive dealerships and consumers. That's why more than 10.5 million people trust us to help with their bank, auto, invest and other financial needs.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "Ally provides $100 per month towards student loans, with a lifetime maximum cap of $10,000. The company is also reimbursing tuition up to $10,000 per year — a more than 50% increase in reimbursement offerings",
            "link_to_benefit_details": "https://www.benefitnews.com/news/ally-financial-helps-employees-pay-for-education"
        },
        {
            "uuid": "9c02fde6-4988-4f6f-9d5f-a0e56a162e46",
            "company_name": "American Family Insurance",
            "job_scraper": true,
            "createdAt": "2022-05-27T22:45:03.246Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://amfam.wd1.myworkdayjobs.com/Careers?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com",
            "company_website": "https://www.amfam.com/",
            "industry": "Insurance",
            "imagelink": "https://ucarecdn.com/b198e1f0-948d-4037-a009-3075f4a4750d/americanfamilyinsurance.png",
            "company_summary": "At American Family Insurance, we're committed to inspiring dreamers and helping them pursue and protect their dreams.",
            "company_description": "For more than 90 years, American Family Insurance has built its reputation on sound principles. We strive to provide you industry-leading service, exceptional claims experience and products that build long-term relationships. \n  \n  This is accomplished by treating policyholders fairly in a helpful and caring way and making it easy and convenient to work with us. We know our customers like family.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "For qualifying employees who have graduated with an associate’s degree or above and have student loan debt, American Family provides a monthly contribution of $100 for student loan repayment with a lifetime maximum of $10,000.",
            "link_to_benefit_details": "https://www.amfam.com/about/corporate-responsibility/people"
        },
        {
            "uuid": "53a34961-62b4-4487-97e7-a2f408381a9f",
            "company_name": "Andersen Tax",
            "job_scraper": true,
            "createdAt": "2022-06-29T04:17:40.703Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://www.andersen.com/careers/?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com",
            "company_website": "https://www.andersen.com/",
            "industry": "Financial Services",
            "imagelink": "https://ucarecdn.com/9b662221-c385-4822-97ae-80685a488de0/andersen-tax-logo.png",
            "company_summary": "Andersen provides a wide range of tax, valuation, financial advisory and related consulting services to individual and commercial clients.",
            "company_description": "We specialize in full service individual and business entity tax compliance and consulting. Our clients are at the center of our operating model which is structured to allow us to be entrepreneurial and proactive in our approach, and enables our Managing Directors to roll up their sleeves and work directly with you. \n  \n  As an Andersen client, the professionals you get to know in your first meeting are the same professionals who will be working with you throughout the process.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "The firm is offering any regular, full-time employee a benefit of $100 a month for 60 months with a $6,000 lump-sum trailer at the end of the five-year period, or a total of $12,000, toward their student loan debt.",
            "link_to_benefit_details": "https://andersen.com/pressroom/andersen-tax-llc-to-launch-new-student-loan-paydown-plan"
        },
        {
            "uuid": "1b217487-9c6b-4921-a712-dbea6754d0c6",
            "company_name": "Atticus",
            "job_scraper": true,
            "createdAt": "2022-05-27T22:45:03.246Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://boards.greenhouse.io/atticus?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com",
            "company_website": "https://www.atticus.com/",
            "industry": "Legal Services",
            "imagelink": "https://ucarecdn.com/b4eccb81-5fec-4b0c-95ff-058c4403e1f1/atticus.png",
            "company_summary": "We help people in crisis get the aid they need, for free.",
            "company_description": "When you're injured, disabled, or wronged, Atticus gets you all the aid you're entitled to from government, insurance, and courts.\n  \n  At any given time, 15 million Americans are experiencing a crisis that requires urgent help from our legal system or government. The right assistance could transform their lives. But today, most never get it. \n  \n  Atticus is a startup on a mission to change that. We're reinventing a broken space: the $100 billion market for legal services for individuals. We've taken a rare and exclusive commodity - access to expert legal advice and referrals - and made it free and available to everyone.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "Atticus provides up to $1,200/year in student loan repayment assistance.",
            "link_to_benefit_details": "Listed on every job posting"
        },
        {
            "uuid": "48fb7b9d-2535-48af-8031-189a862511a7",
            "company_name": "Bellco Credit Union",
            "job_scraper": true,
            "createdAt": "2022-06-29T04:17:40.703Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://www.bellco.org/about-bellco/careers/?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&utm_ref=dwindlestudentdebt.com",
            "company_website": "https://www.bellco.org/",
            "industry": "Banking",
            "imagelink": "https://ucarecdn.com/8abf5a2c-6ed6-481e-806a-243132d75561/bellco-credit-union-logo.png",
            "company_summary": "Serving Colorado's financial needs since 1936.",
            "company_description": "Founded in 1936, Bellco Credit Union is one of the largest credit unions in Colorado, with more than $4 billion in assets, over 320,000 members and 25 branches in the Denver metro area and on the Western Slope. But despite its size, Bellco remains committed to its members and local communities, providing financial and volunteer support for numerous organizations. \n  \n  As a member-owned not-for-profit business, Bellco delivers advantages that include lower interest rates on loans, higher yields on savings, shared branching with a national network of credit unions and access to thousands of surcharge-free ATMs. \n  \n  Bellco offers a full range of financial products and services including checking, savings, investment services, mortgage loans, auto loans and business products and is proud to be an industry leader in technology and environmentally friendly business practices.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "Student Loan Repayment Program (SLAY): Receive up to $10,000 towards your student loans payments.",
            "link_to_benefit_details": "https://www.bellco.org/EmployeeBenefits.aspx"
        },
        {
            "uuid": "507e89de-9ed6-4a5b-b443-0c2f40d5988f",
            "company_name": "Carhartt",
            "job_scraper": true,
            "createdAt": "2022-06-29T04:17:40.703Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://www.carhartt.com/careers?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com",
            "company_website": "https://www.carhartt.com",
            "industry": "Retail Apparel and Fashion",
            "imagelink": "https://ucarecdn.com/7c4f8a59-3732-4ee9-95a2-915713980ad2/carhartt.png",
            "company_summary": "Outworking them all since 1889.\n  \nCarhartt manufactures premium clothing known for exceptional durability, comfort, quality of construction and fit that you can feel in the fabrics and see in the performance.",
            "company_description": "Established in Detroit in 1889, our corporate headquarters is today located in Dearborn, Michigan and our U.S. facilities are located in Kentucky and Tennessee. \n  \n  We have company-owned retail locations throughout the U.S. and our flagship store is located in Midtown, Detroit. We are proud to be making best-in-class apparel for the active worker. \n  \n  Our work environment is friendly, business casual, family oriented and welcoming to all. Our dedication to quality is not only reflected in our products but also in our people. \n  \n  At Carhartt, we are committed to providing our consumer with a brand they can trust and depend on, our associates with career challenges and rewards and our communities with support and assistance.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "Carhartt offers employees a $50 monthly contribution toward their student loan debt up to a lifetime maximum of $10,000.\n\nThe monthly payments go directly to the employees’ student loan service providers and are applied to principal on their loans.\n\nThe plan is open to all full- and part-time employees, both union and nonunion. Nonunion employees are eligible after 30 days with the company, while union employees are eligible after 90 days.",
            "link_to_benefit_details": "https://www.benefitnews.com/news/carhartt-adds-student-loan-perk-to-benefits-package"
        },
        {
            "uuid": "10c4e9dc-588c-4721-b36a-d6269fa2379e",
            "company_name": "Carvana",
            "job_scraper": true,
            "createdAt": "2022-05-27T22:45:03.246Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://www.carvana.com/careers/all-listings?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com",
            "company_website": "https://www.carvana.com/",
            "industry": "Internet",
            "imagelink": "https://ucarecdn.com/82427ec6-ac28-4494-bbc5-3077a1384993/carvana.png",
            "company_summary": "Carvana's mission is to change the way people buy and sell cars. At Carvana, We'll Drive You Happy.",
            "company_description": "Carvana offers an intuitive and convenient online car buying, selling, and financing experience. \n  \n  Carvana.com enables customers to quickly and easily shop more than 55,000 vehicles, finance, trade in or sell their current vehicle to Carvana, sign contracts and schedule delivery or pickup at one of its patented, automated Car Vending Machines.\n  \n  Carvana is a Fortune 500 company, providing as-soon-as-next-day delivery to customers in over 300 U.S. markets.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "Carvana will contribute up to $1,000 per year for employees to pay down their student loan debt.",
            "link_to_benefit_details": "https://www.benefitnews.com/news/carvana-rolls-out-student-loan-repayment-perk"
        },
        {
            "uuid": "9a21ebd1-d9e5-416e-9f70-a9d067d9ae53",
            "company_name": "Chegg",
            "job_scraper": true,
            "createdAt": "2022-06-28T17:40:52.417Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://osv-chegg.wd5.myworkdayjobs.com/Chegg?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com",
            "company_website": "https://www.chegg.com/",
            "industry": "Internet - Education",
            "imagelink": "https://ucarecdn.com/2c6490dc-2c37-4dc7-a1a8-3c12b28c6a15/chegg-logo.png",
            "company_summary": "The leading student-first connected learning platform.",
            "company_description": "Chegg's Student Hub makes higher education more affordable and more accessible, all while improving student outcomes. \n  \n  Chegg is a publicly-held company based in Santa Clara, CA with offices in San Francisco, New York, Portland, India, Israel, Berlin, and Ukraine. Chegg Student Hub Services Includes; Chegg Study, Tutoring, Writing Tools, Math Help, Test Prep, Careers Search, Internship Admissions, and College Admissions.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "Chegg pays $1,000 per year to employees with student loan debt.\n\nOn top of this, The Equity for Education benefit applies to any Chegg US employee with student debt, irrespective of whether they attended a 2- or 4-year college, or ultimately graduated.\n\nUnder the new Chegg program, entry level employees through manager level, who have at least two years tenure at Chegg will receive up to $5,000 annually. Employees at the Director or Vice-President level are eligible for up to $3,000 annually.",
            "link_to_benefit_details": "https://investor.chegg.com/Press-Releases/press-release-details/2019/Chegg-reveals-first-of-its-kind-equity-plan-to-help-its-US-employees-pay-off-their-student-debt/default.aspx"
        },
        {
            "uuid": "6a864ab5-73a8-4fd0-9044-5ac9ca30256b",
            "company_name": "ChowNow",
            "job_scraper": true,
            "createdAt": "2022-05-27T22:45:03.246Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://get.chownow.com/careers/?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com",
            "company_website": "https://get.chownow.com/",
            "industry": "Internet Publishing",
            "imagelink": "https://ucarecdn.com/768db4bd-9270-4692-a5b3-0b116016e300/chownow.png",
            "company_summary": "We help local restaurants thrive.",
            "company_description": "ChowNow powers branded online ordering systems for independent restaurants across the US via restaurants own websites, on Facebook and Google pages, through ChowNow-created apps, and via ChowNow's website while also providing our restaurant partners key customer insights and marketing support. \n  \n  We do all of this for a reasonable monthly fee, without the predatory third-party commissions charged by our competitors. \n  \n  Using ChowNow allows diners to connect with the best independent restaurants in their communities to order takeout (and in some cases delivery) in a way that's sustainable and fair to restaurants.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "ChowNow currently caps contributions at $500 per year but plans to increase that to $1,000 in the future.",
            "link_to_benefit_details": "https://news.yahoo.com/private-sector-jobs-help-repay-130000505.html"
        },
        {
            "uuid": "cf84302c-9cb8-4a0b-8eb7-ef19d696621f",
            "company_name": "Commonbond",
            "job_scraper": true,
            "createdAt": "2022-05-27T22:45:03.246Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://www.commonbond.co/careers?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com",
            "company_website": "https://www.commonbond.co/",
            "industry": "Financial Services",
            "imagelink": "https://ucarecdn.com/c40e9919-8230-4e0e-aba6-5b049db082b8/commonbond.png",
            "company_summary": "Your friend in finance.",
            "company_description": "CommonBond has built a values-driven, customer-centric fintech company. Our mission is to change the way people think about their personal finances and financial independence. \n  \n  We accomplish this by offering products that increase monthly cash flow for consumers, leverage state-of-the art technology, and deliver award-winning customer service",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "We help employees pay off student loans to the tune of $100 a month until the loans are paid off.",
            "link_to_benefit_details": "https://joinjuno.com/financial-literacy/student-loans/25-companies-that-help-employees-pay-off-student-loans"
        },
        {
            "uuid": "8d9799e8-1332-4c49-9ed2-89d23e299d3b",
            "company_name": "Connelly Partners",
            "job_scraper": true,
            "createdAt": "2022-06-29T04:17:40.703Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://www.connellypartners.com/careers/?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com",
            "company_website": "https://www.connellypartners.com/",
            "industry": "Advertising Services",
            "imagelink": "https://ucarecdn.com/db4f133a-e9c1-48c0-a61f-8d9c0d5e4e15/connelly-partners.png",
            "company_summary": "We're an advertising and marketing agency who believes in human emotions and the power to be \"Defiantly Human.\"",
            "company_description": "As the largest independent agency in New England today, we are 170 Defiantly Human people that believe in the power of data but also the reality of emotion. \n  \n  We believe that great data informs great creative and strategy, but there are some things only humans can do like buy your products and services. \n  \n  We exist in defense of humans, with understanding of humans and commitment to humans. \n  \n  We believe in the power of empathy and that our responsibility is to see the world through the eyes of our clients, their customers and our employees. \n  \n  We fit best with brands that aspire to be Modern Brands, brands who acknowledge the changing rules of marketing and want what it takes to prepare for tomorrow.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "Connelly Partners will put up to $100 per month toward its employees’ student loan payments.\n\nWhat’s more, new employees will receive a $1,000 signing bonus that can be put toward student loans.\n\nOnce employees hit their five-year anniversary with Connelly Partners, they will receive another $1,000 bonus toward their loans.",
            "link_to_benefit_details": "https://studentloanhero.com/featured/companies-that-pay-off-student-loans/"
        },
        {
            "uuid": "3179bf18-b0a0-4285-962f-feca8e228782",
            "company_name": "Crew Carwash",
            "job_scraper": true,
            "createdAt": "2022-05-27T22:45:03.246Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://crewcarwash.com/apply-now?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com",
            "company_website": "https://crewcarwash.com/",
            "industry": "Retail",
            "imagelink": "https://ucarecdn.com/9251199c-594e-4fb4-808a-f8e6ae8df6a5/crew-carwash.png",
            "company_summary": "An Indiana based, multi-generational family business built to last.",
            "company_description": "For over 70 years, we've held fast to one goal - delivering a clean, quick carwash, every time, with a smile to the customer. \n  \n  As our Founder, Joe Dahm often reminds us, we're really in the people business. We just happen to wash cars. And, we believe much of our success stems directly from treating our boss, the customer, to the best possible experience every time they visit.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "We will pay $1,200 per year, $100 each month, toward employee's student loans, which is paid directly to the lender.",
            "link_to_benefit_details": "https://www.carwash.com/crew-carwash-student-loan-assistance-plan/"
        },
        {
            "uuid": "aa5b4f15-0194-4603-806f-b0e739291b0e",
            "company_name": "CSAA Insurance Group",
            "job_scraper": true,
            "createdAt": "2022-05-27T22:45:03.246Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://careers.csaa-insurance.aaa.com/us/en/search-results?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com",
            "company_website": "https://csaa-insurance.aaa.com/content/aaa-ie/b2c/en/homepage.html",
            "industry": "Insurance",
            "imagelink": "https://media-exp1.licdn.com/dms/image/C560BAQHMcD93Iqkt5g/company-logo_200_200/0/1569616339615?e=2147483647&v=beta&t=G7rFSLET7kgyfLwpXrgQ9UdUqt02QfchWd8R2FhnSGw",
            "company_summary": "We are an insurance company and personalized service is at the heart of what we do.",
            "company_description": "We aspire to be the number one insurer in AAA member households across the markets we serve, and are motivated by the growth of our business, the pursuit of excellence, and the innovation within our company and industry. \n  \n  We find that by being committed to our employees results in their commitment to provide AAA members with exemplary service. This two-way commitment allows us to achieve moreâ€”together.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "We allow full and part-time employees to use up to 4% of their employer-matched retirement benefit to pay down their student debt.\n\nOnce workers contribute 2% of their salaries to their 401(k), they can choose to direct the remaining 1% to 4% of their 6% employer-matched funds toward paying down their student loans.",
            "link_to_benefit_details": "https://www.benefitnews.com/news/csaa-insurance-adds-student-loan-401-k-matching-benefit"
        },
        {
            "uuid": "b460b6d9-14b0-46c3-b81a-fb059e47d8dc",
            "company_name": "Easterseals NH",
            "job_scraper": true,
            "createdAt": "2022-05-27T22:45:03.246Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://us62e2.dayforcehcm.com/CandidatePortal/en-US/eastersealsnh?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com",
            "company_website": "https://www.easterseals.com/nh/",
            "industry": "Non-Profit Organization",
            "imagelink": "https://ucarecdn.com/ec9cadd6-0028-4103-af20-e72f1c8c9ae4/easterseals-nh.png",
            "company_summary": "We provide exceptional services to ensure that all people with disabilities or special needs and their families have equal opportunities to live, learn, work and play in their communities.",
            "company_description": "For over 84 years, Easterseals New Hampshire has provided exceptional services to ensure we change the way the world defines and views disability by making profound, positive differences in people's lives every day.\n  \n  Easterseals NH services include autism services, inclusive child care and early intervention, special education, medical rehabilitation, camping and recreation, vocational services, senior services, substance use services, adult day programs, community-based services, individual service options, transportation services, residential service options, and veteran services.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "Easterseals provides financial support to employees who have student loans from educational courses / degrees which meet the criteria outlined in the Student Loan Repayment Policy.\n  \nActive employees who are classified as full-time (30+hours per week) with at least one year of continuous service immediately prior to their request for loan repayment are eligible to apply for loan repayment.",
            "link_to_benefit_details": "https://ggbportal.com/easterseals/images/ES_NH_Enrollment_Guide_2021.pdf"
        },
        {
            "uuid": "9ab8c498-d718-4c6a-b36f-8329416c0987",
            "company_name": "Estee Lauder",
            "job_scraper": true,
            "createdAt": "2022-05-27T22:45:03.246Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://jobs.elcompanies.com/estee-lauder-companies/jobs?page=1&location=&keywords=&locations=,,United%20States?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com",
            "company_website": "https://www.esteelauder.com/",
            "industry": "Personal Care Product Manufacturing",
            "imagelink": "https://ucarecdn.com/ce1fbebe-fa1a-4a80-bca7-33a300daa0ba/estee-lauder.png",
            "company_summary": "We are the global leader in prestige beauty - delighting consumers with transformative products and experiences, inspiring them to express their individual beauty.",
            "company_description": "We are the only company focused solely on prestige makeup, skin care, fragrance and hair care with a diverse portfolio of 25+ brands sold in approximately 150 countries and territories. \n  \n  Infused throughout our organization is a passion for creativity and innovation - a desire to push the boundaries and invent the unexpected - as we continue the bold work of our founder Estée Lauder.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "We offer our Student Loan Contribution Program, contributing up to $100 per month towards an employee's loan with a lifetime maximum of $10,000.",
            "link_to_benefit_details": "https://www.elcompanies.com/en/careers/why-work-here/learning-and-development"
        },
        {
            "uuid": "b1579fd1-c72d-4322-b821-1839e64590b3",
            "company_name": "Fidelity Investments",
            "job_scraper": true,
            "createdAt": "2022-05-27T22:45:03.246Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://jobs.fidelity.com/job-search-results?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com",
            "company_website": "https://www.fidelity.com/",
            "industry": "Financial Services",
            "imagelink": "https://ucarecdn.com/42b1ed6e-5bb5-47ca-9bb0-693920604e52/fidelity-investments.png",
            "company_summary": "We help over ~40 million people feel more confident in their most important financial goals, manage employee benefit programs for nearly 23,000 businesses, and support more than 3,600 advisory firms* with innovative investment and technology solutions to grow their businesses.",
            "company_description": "Privately held for nearly 70 years, we've always believed by providing investors with access to the information and expertise, we can help them achieve better results. \n  \n  That's been our approach- innovative yet personal, compassionate yet responsible, grounded by a tireless work ethic - it is the heart of the Fidelity way.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "Fidelity helps you get a step ahead by paying down your loans so you can save on interest, with up to $15K in contributions.",
            "link_to_benefit_details": "https://jobs.fidelity.com/benefits/"
        },
        {
            "uuid": "490a6e3e-a7ee-453f-bc27-e47b9608eb3f",
            "company_name": "First Republic Bank",
            "job_scraper": true,
            "createdAt": "2022-05-27T22:45:03.246Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://careers.firstrepublic.com/?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com",
            "company_website": "https://www.firstrepublic.com/",
            "industry": "Banking",
            "imagelink": "https://ucarecdn.com/b92c5ea8-4f19-4a01-b440-0ab6c7a57ec9/first-republic-bank.png",
            "company_summary": "It's a privilege to serve you.®",
            "company_description": "First Republic is a full-service financial institution specializing in private banking and private business banking. In addition, our wealth management affiliates offer investment, trust and wealth management services. \n  We deliver personalized solutions to help both individuals and businesses meet their financial goals, with over 80 Preferred Banking Offices located primarily in urban coastal markets, including San Francisco, New York, Boston and Los Angeles.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "$100 per month of loan repayment during the first year of enrollment in the benefit.\n\n$150 per month of loan repayment during the second year of enrollment in the benefit.\n\n$200 per month of loan repayment thereafter while enrolled in the benefit until the debt is repaid.\n\nThe program is offered by First Republic to all full-time or part-time employees who work a minimum of 20 hours a week. The benefit is also available to First Republic employees who have taken out educational loans on behalf of their children. First Republic will make the contribution, during employment at the Bank, for the life of the loan.",
            "link_to_benefit_details": "https://www.firstrepublic.com/about-us/careers/benefits & https://news.firstrepublic.com/news-releases/news-release-details/first-republic-bank-expands-innovative-student-loan-repayment"
        },
        {
            "uuid": "a1348534-beca-415a-b600-258e311c9b68",
            "company_name": "Freddie Mac",
            "job_scraper": true,
            "createdAt": "2022-05-27T22:45:03.246Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://corporate.ford.com/careers/job-opportunities.html?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com",
            "company_website": "https://www.freddiemac.com/",
            "industry": "Financial Services",
            "imagelink": "https://ucarecdn.com/1ef7f1ab-f6e8-4dfa-9052-bd7d8d992896/freddie-mac.png",
            "company_summary": "We're on a mission to make home possible for homebuyers and renters across the U.S.",
            "company_description": "Freddie Mac makes home possible for millions of families and individuals by providing mortgage capital to lenders. \n  Since our creation by Congress in 1970, weâ€™ve made housing more accessible and affordable for homebuyers and renters in communities nationwide. We are building a better housing finance system for homebuyers, renters, lenders and taxpayers.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "We will help pay down an eligible employee's student loan by making contributions totaling up to $9,000 over a five-year period.",
            "link_to_benefit_details": "https://careers.freddiemac.com/us/en/benefits"
        },
        {
            "uuid": "235d397b-9e48-44f1-afb9-e74f7310072f",
            "company_name": "Google",
            "job_scraper": true,
            "createdAt": "2022-06-29T04:17:40.703Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://careers.google.com/jobs/results/?ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_source=dwindlestudentdebt.com",
            "company_website": "google.com",
            "industry": "Internet",
            "imagelink": "https://ucarecdn.com/bd58c18f-0ce0-4680-8b93-99a8d768a1b9/google.png",
            "company_summary": "Our mission is to organize the world's information and make it universally accessible and useful.",
            "company_description": "Our mission is to organize the world's information and make it universally accessible and useful. A problem isn't truly solved until it's solved for all. Googlers build products that help create opportunities for everyone, whether down the street or across the globe. \n  \n  Bring your insight, imagination and a healthy disregard for the impossible. Bring everything that makes you unique. Together, we can build for everyone.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "Google will match up to $2,500 in loan payments per employee each year.",
            "link_to_benefit_details": "https://www.businessinsider.com/google-helping-employees-pay-off-student-loan-debt-2020-9"
        },
        {
            "uuid": "02252ceb-0b5f-4e29-aed5-aa1956d20adb",
            "company_name": "Guild Education",
            "job_scraper": true,
            "createdAt": "2022-06-29T04:17:40.703Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://www.guildeducation.com/about-us/careers/?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com",
            "company_website": "guildeducation.com",
            "industry": "Education Administration Programs",
            "imagelink": "https://ucarecdn.com/f4a0251e-7472-4589-8d7c-54a254f110f0/guild-education.png",
            "company_summary": "We're on a mission to unlock opportunity for America's workforce through education and upskilling.",
            "company_description": "Guild Education is on a mission to unlock opportunity for America's workforce through education and upskilling, with a double bottom-line business model that does well by doing good.\n  \n  Guild works with leading Fortune 1000 employers such as The Walt Disney Company, Walmart, Discover, Chipotle and Lowe's to transform their education & upskilling programs through Guild's technology platform, payments system and learning marketplace. \n  \n  With nearly 800 employees and a growing customer base, Guild is a fast-growing company that was recognized as a winner of Fast Company's 2020 World Changing Ideas award and a CNBC Disruptor 50 company for its work at the intersection of education and the future of work.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "Guild offers student loan reimbursement.",
            "link_to_benefit_details": "https://www.guildeducation.com/about-us/careers/?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com"
        },
        {
            "uuid": "ab121450-84f1-4205-827a-bb9dc0d19f5e",
            "company_name": "HCA Healthcare",
            "job_scraper": true,
            "createdAt": "2022-06-29T04:17:40.703Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://careers.hcahealthcare.com/search/jobs?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com",
            "company_website": "https://hcahealthcare.com/",
            "industry": "Hospitals and Healthcare",
            "imagelink": "https://ucarecdn.com/ffa31210-a157-4f4a-9784-b9937ae92b71/hca-healthcare.png",
            "company_summary": "At HCA Healthcare, we are driven by a single mission: Above all else, we are committed to the care and improvement of human life.",
            "company_description": "HCA Healthcare is one of the nation's leading providers of healthcare services, comprising 182 hospitals and approximately more than 2,300 sites of care, including surgery centers, freestanding ERs, urgent care centers, and physician clinics, in 20 states and the United Kingdom. \n  With more than 283,000 colleagues driven by one purpose - to give patients healthier tomorrows - we are excited about the future of medicine and believe we are uniquely positioned to play a leading role in the transformation of clinical care.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "Offers a monthly benefit of $100 (full-time) or $50 (part-time) to help you repay your student loans for degrees you have already completed.",
            "link_to_benefit_details": "https://connect.talemetry.com/system/production/assets/258989/original/HCA_2021_RecruitingBrochure_FINAL.pdf"
        },
        {
            "uuid": "df2c5743-dca8-433b-96de-e5d6776524a7",
            "company_name": "Honeywell",
            "job_scraper": true,
            "createdAt": "2022-06-29T04:17:40.703Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://careers.honeywell.com/us/en/?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com",
            "company_website": "https://honeywell.com",
            "industry": "Appliances, Electrical, and Electronics Manufacturing",
            "imagelink": "https://ucarecdn.com/c3e3f416-1a67-4d8f-8bc5-12f86f4cc8b8/honeywell.png",
            "company_summary": "We believe what happens tomorrow is determined by what we do today.",
            "company_description": "Honeywell is a Fortune 100 company that invents and manufactures technologies to address tough challenges linked to global macrotrends such as safety, security, and energy. \n  With approximately 110,000 employees worldwide, including more than 19,000 engineers and scientists, we have an unrelenting focus on quality, delivery, value, and technology in everything we make and do.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "$150 per month with a $10,000 maximum limit.",
            "link_to_benefit_details": "https://www.foxbusiness.com/personal-finance/employer-student-loan-repayment-assistance & https://hypepotamus.com/news/honeywell-student-loan-benefits/"
        },
        {
            "uuid": "f3f5e51d-feda-42af-a114-34d360267023",
            "company_name": "Hulu",
            "job_scraper": true,
            "createdAt": "2022-05-27T22:45:03.246Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://jobs.disneycareers.com/search-jobs?acm=ALL&alrpm=ALL&ascf=[%7B%22key%22:%22custom_fields.IndustryCustomField%22,%22value%22:%22Disney+Streaming%22%7D,%7B%22key%22:%22custom_fields.IndustryCustomField%22,%22value%22:%22Hulu%22%7D]",
            "company_website": "https://www.hulu.com/welcome",
            "industry": "Internet",
            "imagelink": "https://ucarecdn.com/cdd40a6a-4047-45ff-b818-dd4340d36981/hulu.png",
            "company_summary": "Hulu is the leading premium streaming service offering live and on-demand TV and movies, with and without commercials, both in and outside the home.",
            "company_description": "Launched in 2008, Hulu has grown to more than 25 million subscribers in the U.S. and is the only service that gives viewers instant access to current shows from every major U.S. broadcast network; libraries of hit TV series and films; and acclaimed Hulu Originals like Emmy® and Golden Globe Award-winning series The Handmaid's Tale, Emmy Award-nominated The Looming Tower, Future Man, Marvel's Runaways and Castle Rock, as well as live news, entertainment and sports from 21st Century Fox, The Walt Disney Company, NBCUniversal, CBS Corporation, The CW, Turner Networks, A+E Networks and Discovery Networks all in one place.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "Hulu will pay up to $1,200 a year per employee to match their student loan payments.",
            "link_to_benefit_details": "https://www.benefitnews.com/news/hulu-binges-on-tuition-benefits-for-employees"
        },
        {
            "uuid": "b1362692-e0bf-4d1e-a0d7-02257dc6abc9",
            "company_name": "Inova Health",
            "job_scraper": true,
            "createdAt": "2022-06-29T04:17:40.703Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://www.inova.org/careers?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com",
            "company_website": "https://www.inova.org/",
            "industry": "Hospitals and Health Care",
            "imagelink": "https://ucarecdn.com/cf7eab53-a863-4ee4-bb01-dbbe15f2fa16/inova-health.png",
            "company_summary": "Inova's mission is to provide world-class healthcare to each person in every community we have privilege to serve.",
            "company_description": "Inova is Northern Virginiaâ€™s leading nonprofit healthcare provider, employing more than 18,000 team members and serving more than 2 million individuals annually through an integrated network of hospitals, primary and specialty care practices, emergency and urgent care centers, outpatient services and destination institutes such as the Inova Heart and Vascular Institute, Inova Schar Cancer Institute and Inova Neuroscience and Spine Institute.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "Inova will provide financial assistance by making a monthly payment to team members’ student loan servicers.\n\nMonthly payments will be $150 if a team member has less than 3 years of continuous service and $250 if a team member has 3 years or more of continuous service. The lifetime maximum is $10,000.",
            "link_to_benefit_details": "https://www.myinovabenefits.org/WorkLife/Education#:~:text=Inova%20will%20provide%20financial%20assistance,The%20lifetime%20maximum%20is%20%2410%2C000."
        },
        {
            "uuid": "3b59484d-2121-4599-9b44-045967a40a59",
            "company_name": "LendEDU",
            "job_scraper": true,
            "createdAt": "2022-05-27T22:45:03.246Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "mailto:support@lendedu.com",
            "company_website": "https://lendedu.com/",
            "industry": "Financial Services",
            "imagelink": "https://ucarecdn.com/33a29a41-cd7f-48e2-a1f2-afd7aaafd68e/lendedu.png",
            "company_summary": "Educated Financial Decisions.",
            "company_description": "LendEDU is a personal finance comparison website. LendEDU's goal is to help you make educated financial decisions when it comes to products like student loans, mortgages, home equity loans, insurance, personal loans, credit cards, and many more. Through LendEDU's free blog, tools, and resources, we want to keep you informed and educated on all things personal finance.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "$200 per month or $2,400 per year to help pay student debt. The benefit is open to all employees and can be applied to both principal and interest.",
            "link_to_benefit_details": "https://www.gobankingrates.com/money/jobs/companies-employees-pay-off-student-loans/"
        },
        {
            "uuid": "2ea26dec-5067-49b0-95b8-c93c9ec535d1",
            "company_name": "Live Nation Entertainment",
            "job_scraper": true,
            "createdAt": "2022-05-27T22:45:03.246Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://livenation.wd1.myworkdayjobs.com/LNExternalSite?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com",
            "company_website": "https://www.livenation.com/",
            "industry": "Entertainment",
            "imagelink": "https://ucarecdn.com/75565027-05d4-44af-9cb9-788490e284e1/live-nation.png",
            "company_summary": "Live Nation produces more concerts, sell more tickets and connects more brands to music than anyone else in the world.",
            "company_description": "Live Nation Entertainment is the global leader in live events and ticketing. With business operations and corporate functions across major divisions including Ticketmaster, Concerts, Media & Sponsorship and Artist Nation, we offer exciting opportunities across every discipline.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "Live Nation is matching employee contributions of up to $100 monthly, or $1,200 a year, up to $6,000. (Employees who have been with the firm for a t least 6 months qualify.)",
            "link_to_benefit_details": "https://www.usatoday.com/story/tech/talkingtech/2017/01/18/live-nation-help-employees-pay-off-student-debt/96690660/"
        },
        {
            "uuid": "51322504-028f-44a0-a08a-943d8b3835df",
            "company_name": "Lockheed Martin",
            "job_scraper": true,
            "createdAt": "2022-06-29T04:17:40.703Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://www.lockheedmartinjobs.com/?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com",
            "company_website": "https://www.lockheedmartin.com/",
            "industry": "Defense and Space Manufacturing",
            "imagelink": "https://ucarecdn.com/10c165e0-8dd2-4b22-b22f-f12cebffa70b/lockheed-martin.png",
            "company_summary": "Customer focus, innovation and purpose are built into everything we do. Lockheed Martin. Your Mission Is Ours®.",
            "company_description": "Headquartered in Bethesda, Maryland, Lockheed Martin is a global security and aerospace company that employs approximately 114,000 people worldwide and is principally engaged in the research, design, development, manufacture, integration and sustainment of advanced technology systems, products and services.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "Invest In Me, which provides college hires with a $150 monthly cash bonus for five years, up to a maximum of $9,000.\n\nYou can use the money to pay down student loans or save for other goals.",
            "link_to_benefit_details": "https://www.forbes.com/advisor/student-loans/companies-that-pay-student-loans/"
        },
        {
            "uuid": "d3edd1a7-809f-4e40-8146-dc0fa06628d2",
            "company_name": "Mclaren Health Care",
            "job_scraper": true,
            "createdAt": "2022-06-29T04:17:40.703Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://www.mclaren.org/main/careers?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com",
            "company_website": "mclaren.org",
            "industry": "Hospitals and Health Care",
            "imagelink": "https://ucarecdn.com/37f528ac-efd8-459d-af66-13c6f190963f/mclaren-health-care.png",
            "company_summary": "McLaren Health Care, headquartered in Grand Blanc, Michigan, is a fully integrated health care delivery system committed to quality, evidence-based patient care and cost efficiency.",
            "company_description": "The McLaren system includes 15 hospitals in Michigan and Ohio, ambulatory surgery centers, imaging centers, a 490-member employed primary and specialty care physician network, commercial and Medicaid HMOs covering approximately 640,000 lives in Michigan and Indiana, home health, infusion and hospice providers, pharmacy services, a clinical laboratory network and a wholly owned medical malpractice insurance company.\n  McLaren operates Michigan's largest network of cancer centers and providers, anchored by the Karmanos Cancer Institute, one of only 51 National Cancer Institute-designated comprehensive cancer centers in the U.S.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "The student loan benefit will be applied like a 401(k) contribution - the service provider will automatically take an amount from McLaren Northern Michigan to apply toward the principal of their employee's student loans each month. This tuition payment is in addition to the employee's monthly loan payment, helping to shorten the length of the loan and reduce interest. The McLaren monthly payment starts at $200 and increases in years two and three if the employee remains with McLaren Northern Michigan. A maximum of $12,000 of funding may be applied toward the employee's student loan.",
            "link_to_benefit_details": "https://www.mclaren.org/main/news/mclaren-northern-michigan-launches-student-loan-re-3650"
        },
        {
            "uuid": "83948567-9f0e-4fec-9cf3-cef596edfb20",
            "company_name": "MidWestOne Bank",
            "job_scraper": true,
            "createdAt": "2022-06-29T04:17:40.703Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://careers-midwestone.icims.com/jobs/search?ss=1&hashed=-435800308&mobile=false&width=980&height=500&bga=true&needsRedirect=false&jan1offset=-300&jun1offset=-240%3Futm_source%3Ddwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com",
            "company_website": "https://www.midwestone.bank/",
            "industry": "Financial Services",
            "imagelink": "https://ucarecdn.com/7bde84f8-010d-4f47-8cb7-9448d8714eb1/midwestone-bank.png",
            "company_summary": "MidWestOne Bank was founded in 1934 with the mission statement \"To take care of our customers...and those who should be. This is the same mission today.",
            "company_description": "Headquartered in Iowa City, Iowa, MidWestOne Bank operates 55 banking offices in Iowa, Minnesota, Wisconsin, Florida and Colorado. As a community bank, MidWestOne focuses on fulfilling all of the possible financial needs of a customer by offering personal banking, small business banking, wealth management, mortgage, and more.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "Full-time employees who have been at the company for more than four years receive $100 a month, with a $10,000 lifetime cap, while full-time employees with less than four years at the bank receive $75 a month. Those employees will receive the full $100 when they enter their fifth year with the bank.\n  \nPart-time employees must work a minimum of 28 hours per week and have at least 30 days of service to qualify for the $50 benefit.",
            "link_to_benefit_details": "https://www.benefitnews.com/news/midwestone-bank-helps-employees-pay-off-student-debt"
        },
        {
            "uuid": "f54c4cff-b0f1-46df-a7e5-486f39ef834c",
            "company_name": "Natixis",
            "job_scraper": true,
            "createdAt": "2022-05-27T22:45:03.246Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://recrutement.natixis.com/jobs/list?hidden_submit=1&amp;keywords=&amp;category=&amp;country=US&amp;city=&amp;contractType=&amp;organization=?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com",
            "company_website": "https://natixis.groupebpce.com/natixis/en/home-j_6.html",
            "industry": "Financial Services",
            "imagelink": "https://media-exp1.licdn.com/dms/image/C560BAQGYmAU5uZzJ5A/company-logo_200_200/0/1631809074130?e=2159024400&v=beta&t=dHpMpWFMeqOYSTPEsQQPdR-Kzmzksc1Fh46eIMBp4nc",
            "company_summary": "Corporate and Investment Banking.",
            "company_description": "Natixis is a leading global financial institution that provides advisory, investment banking, financing, corporate banking and capital markets services to corporations, financial institutions, financial sponsors and sovereign and supranational organizations worldwide.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "Employees will be eligible immediately and as long as they are employed by the company, with monthly payments of $83.33 made directly to the student loan provider up to the life of the loan, or a maximum of $10,000 over a 10-year period.\n  \nFor graduates with the average student debt load of $30,000, that amounts to paying down a third of their loan. The payments also go directly toward the principal, which helps to pay off the loan faster and with less interest over time.",
            "link_to_benefit_details": "https://peoplejoy.com/student-loan-repayment-assistance-benefits/"
        },
        {
            "uuid": "da2c21a8-c60b-4d62-8382-ead286b2b440",
            "company_name": "New York Life Insurance Company",
            "job_scraper": true,
            "createdAt": "2022-05-27T22:45:03.246Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://jobs.newyorklife.com/search/?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com",
            "company_website": "https://www.newyorklife.com/",
            "industry": "Financial Services",
            "imagelink": "https://ucarecdn.com/95bfd250-bbae-4c4f-a600-1421ce89e071/new-york-life-logo.png",
            "company_summary": "For over 175 years, we've been helping people put their love into action.",
            "company_description": "For over 175 years, we've been helping people put love into action. As a mutual company owned by our policyholders*, we hold ourselves to the highest standards of transparency, objectivity, and integrity. Recognized as one of Fortune's World's Most Admired Companies**, we're committed to improving local communities through a culture of giving and volunteerism, supported by our own New York Life Foundation.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "Through Vault Pay, New York Life contributes $170 monthly (over 5 years) towards student loans in good standing which means employees can reduce their debt by up to $10,200 while enrolled. \n  \nThrough Vault Advisor, employees can access tools, resources, and personalized advice to determine the best repayment option for their student loans even if the employee is not eligible for repayment assistance.",
            "link_to_benefit_details": "https://www.newyorklife.com/newsroom/student-loan-repayment-cnbc"
        },
        {
            "uuid": "0221b6d3-cbe1-40bb-b8e3-d8f53c1ceb76",
            "company_name": "Noodles & Company",
            "job_scraper": true,
            "createdAt": "2022-05-27T22:45:03.246Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://apply.jobappnetwork.com/noodles?keywordsFilter=&city=&state=&category=Restaurant%20Management&utm_source=careersite&utm_medium=organic&utm_campaign=RestaurantManagement&?src=CompanyWebsite?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com",
            "company_website": "https://www.noodles.com/",
            "industry": "Restaurants",
            "imagelink": "https://ucarecdn.com/0cf57bbf-57dd-4d18-a9ca-43228716c168/noodles-&-company.png",
            "company_summary": "Our mission is to nourish and inspire every team member, guest and community we serve. All noodles welcome!",
            "company_description": "At Noodles & Company we have 4 core values: We Care, We are Passionate, We Show Pride and We Love Life! We've created a supportive environment that challenges and rewards those who share our mission - to Nourish and Inspire every team member, guest, and community we serve.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "For General Managers, Noodles is also part of the solution in helping pay down student loan debt with a company contribution of $1,000 per year.",
            "link_to_benefit_details": "https://www.noodles.com/careers/perks/"
        },
        {
            "uuid": "fb0f2288-0ae9-4aac-a2c4-14be0a214b3a",
            "company_name": "NVIDIA",
            "job_scraper": true,
            "createdAt": "2022-05-27T22:45:03.246Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://nvidia.wd5.myworkdayjobs.com/NVIDIAExternalCareerSite?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com",
            "company_website": "https://www.nvidia.com/en-us/",
            "industry": "Computer Hardware",
            "imagelink": "https://ucarecdn.com/341860d0-93b4-4897-90ee-929222e0e4f9/nvidia.png",
            "company_summary": "A pioneer in accelerated computing.",
            "company_description": "Our invention of the GPU in 1999 sparked the growth of the PC gaming market, redefined computer graphics and ignited the era of modern AI. NVIDIA is now a full-stack computing company with data-center-scale offerings that are reshaping industry.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "If you graduated within the past three years, you can apply for reimbursement of $6,000 each year to help repay your student loans, up to $30,000!",
            "link_to_benefit_details": "https://www.nvidia.com/en-us/benefits/money/529-college-savings-plans/"
        },
        {
            "uuid": "f28216c0-c922-4da3-947d-42fc473dbd6b",
            "company_name": "Peloton",
            "job_scraper": true,
            "createdAt": "2022-05-27T22:45:03.246Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://www.onepeloton.com/careers?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com",
            "company_website": "https://www.onepeloton.com/",
            "industry": "Health, Wellness & Fitness",
            "imagelink": "https://ucarecdn.com/5d9c5374-b56f-4e7e-96e8-a51d3c22bb16/peloton.png",
            "company_summary": "Peloton is the leading interactive fitness platform globally, with a passionate community of more than 7 million Members in the US, UK, Canada, Germany, and Australia.",
            "company_description": "Peloton makes fitness entertaining, approachable, effective, and convenient, while fostering social connections that motivate its Members to commit to their fitness journeys. \n  Consumers can access the Peloton library with thousands of live and on-demand classes at the gym, at home, on the road, or wherever they choose to move, through the Peloton Bike, Peloton Tread, Peloton Bike+, Peloton Guide, and Peloton App on any iOS or Android device and select smart TVs.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "Peloton contributes $100 a month to accelerate the pay-off of student loan debt held by its employees.",
            "link_to_benefit_details": "https://www.gradifi.com/pr/gradifi-partners-with-peloton-to-offer-employee-student-loan-repayment-benefit"
        },
        {
            "uuid": "6e2480e7-322a-42f7-8160-7a972c6f1299",
            "company_name": "Penguin Random House",
            "job_scraper": true,
            "createdAt": "2022-05-27T22:45:03.246Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://jobsearch.createyourowncareer.com/PRH_US/search/?q=&locationsearch=",
            "company_website": "https://www.penguinrandomhouse.com/",
            "industry": "Publishing",
            "imagelink": "https://ucarecdn.com/4ccc1d75-b248-4e0c-b7ed-f451040ac6dd/penguin-random-house.png",
            "company_summary": "Our mission is to ignite a universal passion for reading by creating books for everyone.",
            "company_description": "Penguin Random House is the world's largest trade book publisher. Worldwide, the company is comprised of the adult and children's fiction and nonfiction print and digital trade book publishing businesses of Penguin and Random House in the U.S., U.K., Canada, Australia, New Zealand, India, and South Africa, and Penguin's trade publishing activity in Asia and Brazil; DK worldwide; and Penguin Random House Grupo Editorial's Spanish-language companies in Spain, Mexico, Argentina, Uruguay, Colombia, and Chile.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "We are offering a loan repayment of up to $1,200 annually ($100/month) totaling a maximum of $9,000 over 7.5 years for full-time eligible employees,.\n  \nRegular part-time employees are eligible to receive $75/month for up to 7.5 years adding up to $6,750.",
            "link_to_benefit_details": "https://www.benefitnews.com/news/penguin-random-house-to-offer-student-loan-repayment-benefit-in-2017"
        },
        {
            "uuid": "bfc9423b-af59-4b08-b023-8a5208c99a3a",
            "company_name": "Powertex Group",
            "job_scraper": true,
            "createdAt": "2022-06-29T04:17:40.703Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://powertexgroup.com/careers?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com",
            "company_website": "https://powertexgroup.com/",
            "industry": "Advertising Services",
            "imagelink": "https://ucarecdn.com/7151acf0-b760-401a-bea2-606ed719a896/powertex-group.png",
            "company_summary": "Your story. Our craft. Branded merchandise solutions made for your business.",
            "company_description": "Powertex is a full-service branded merchandise supplier, specializing in not only providing high quality, cost-competitive custom products, but also in providing flexible, turn-key program services that help our customers make real life connections with their brand fans, employees, retail partners, and corporate stakeholders.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "$1,200 per year to repay their student loans, and expects approximately 25% of its employees to enroll in the program.",
            "link_to_benefit_details": "https://www.forbes.com/sites/zackfriedman/2016/12/19/student-loan-repayment-benefit/?sh=201da7641d6f"
        },
        {
            "uuid": "97859559-e34b-48c9-a129-3c13a3f2add2",
            "company_name": "Public Prep",
            "job_scraper": true,
            "createdAt": "2022-06-29T04:17:40.703Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://www.publicprep.org/careers?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com",
            "company_website": "publicprep.org",
            "industry": "Education Administration Programs",
            "imagelink": "https://ucarecdn.com/f33c45d1-7737-4ad8-884a-ea93e2dad84f/public-prep.png",
            "company_summary": "Public Prep is an award-winning network of charter schools across Manhattan and the Bronx and the nation's first non-profit tuition-free charter school network that develops exceptional Pre-K, and single-gender elementary and middle public schools.",
            "company_description": "We envision a world where every scholar realizes their greatness inside and outside of school, and where classrooms are beacons of the community, fostering courageous learners, critical thinkers, and resilient leaders with strong personal agency. \n  Our network comprises 6 schools across 5 campuses in the Lower East Side and Bronx, serving 2,100 scholars in grades PreK-8: \n  Girls Prep Bronx Elementary School (Grades Pre-K-5) \n  Girls Prep Bronx Elementary School II (Grades Pre-K-2) \n  Girls Prep Bronx Middle School (Grades 6-8)\n  Girls Prep Lower East Side Elementary School (Grades PreK-4)\n  Girls Prep Lower East Side Middle School (Grades 5-8)\n  Boys Prep Bronx (Grades K-8)",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "Our partnership with PeopleJoy has enabled Public Prep to support our employees through the reduction of student loan debt!\n  \nWe offer up to 10% matching of minimum monthly payments. A great way to chip away at student loan debt.",
            "link_to_benefit_details": "https://www.publicprep.org/careers?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com"
        },
        {
            "uuid": "dbb455d4-ce9b-4f4f-b5f4-b71ec97ed3d8",
            "company_name": "Pure Insurance",
            "job_scraper": true,
            "createdAt": "2022-05-27T22:45:03.246Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://pureinsurance.wd5.myworkdayjobs.com/PURE?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com",
            "company_website": "https://www.pureinsurance.com/",
            "industry": "Insurance",
            "imagelink": "https://ucarecdn.com/186af743-247a-45fd-ac63-6d6a492e8c37/pure-insurance.png",
            "company_summary": "PURE is a property and casualty insurance company designed exclusively for successful, responsible families.",
            "company_description": "We opened for business more than 15 years ago with the goal of offering something different in the insurance space: a company focused on doing what's right for our membership (policyholders), one that promotes transparency and alignment of interests, and delivers greater value.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "$100 a month toward your student loans.",
            "link_to_benefit_details": "https://www.pureinsurance.com/newsroom/student-debt-relief-for-employees"
        },
        {
            "uuid": "efd01b7f-eeef-473f-8764-79abd49dac49",
            "company_name": "PwC",
            "job_scraper": true,
            "createdAt": "2022-05-27T22:45:03.246Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://jobs.us.pwc.com/search-jobs?fl=6252001,4566966&fcf=[%7B%22Value%22:%22Entry+level+jobs%22,%22Key%22:%22salary_time%22%7D]?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com",
            "company_website": "https://www.pwc.com/us/en",
            "industry": "Accounting",
            "imagelink": "https://ucarecdn.com/fc237bcd-afd3-413d-a930-448d425ad015/pwc.png",
            "company_summary": "At PwC, our purpose is to build trust in society and solve important problems.",
            "company_description": "We're a network of firms in 155 countries with over 284,000 people who are committed to delivering quality in assurance, advisory and tax services.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "As a participating associate or senior associate, PwC's SLP benefit will pay up $1,200 a year towards your student loan!\n  \nOver time, this may help to reduce student loan principal and interest obligations by as much as $10,000, and shorten loan payoff by up to three years.",
            "link_to_benefit_details": "https://www.pwc.com/us/en/careers/why-pwc/employee-benefits.html"
        },
        {
            "uuid": "32cb1207-a615-4dec-a659-7d781d667cad",
            "company_name": "RubiconMD",
            "job_scraper": true,
            "createdAt": "2022-06-29T04:17:40.703Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://boards.greenhouse.io/rubiconmd?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com",
            "company_website": "https://www.rubiconmd.com/",
            "industry": "IT Sevices and IT Consulting",
            "imagelink": "https://ucarecdn.com/fa2586ee-5e0f-4899-a573-ec0e88f40647/rubiconmd.png",
            "company_summary": "Your virtual front door to specialty care.",
            "company_description": "RubiconMD is leading the mission to democratize medical expertise through its virtual-first specialty care solutions. \n  The RubiconMD eConsult and Behavioral Health platforms remove barriers to specialty expertise by rapidly connecting primary care clinicians to a board-certified panel of experts. \n  These solutions empower clinicians to deliver higher-quality care plans in a timely manner. RubiconMD eliminates unnecessary referrals and services, reduces patient wait times and travel burdens, and allows primary care to practice at the top of their license.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "$200 per month, totaling $2,400 per year with no cap.",
            "link_to_benefit_details": "https://peoplejoy.com/companies-that-offer-student-loan-repayment/"
        },
        {
            "uuid": "7b10c203-2f2e-4e64-bee3-4283610e88e5",
            "company_name": "SoFi",
            "job_scraper": true,
            "createdAt": "2022-05-27T22:45:03.246Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://www.sofi.com/careers/?ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_source=dwindlestudentdebt.com",
            "company_website": "https://www.sofi.com/",
            "industry": "Financial Services",
            "imagelink": "https://ucarecdn.com/a6fd90df-96f8-4edd-a6e0-e120238d8ef3/sofi.png",
            "company_summary": "SoFi helps you save, spend, earn, borrow, invest, and protect your money all in one app.",
            "company_description": "SoFi is a values-driven company on a mission to help our members get their money right. We create modern financial products and services that help people borrow, save, spend, invest, and protect their money better, so that they can achieve financial independence and realize their ambitions - from owning a home to saving for retirement, paying off their student loans, and more.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "We want to help our employees achieve financial freedom, just like our members. That's why we contribute $200 per month toward your student loans to help pay down your debt plus free financial classes.",
            "link_to_benefit_details": "https://www.sofi.com/careers/"
        },
        {
            "uuid": "063dc58d-3d94-447a-a363-4d3d6d483338",
            "company_name": "Sotheby's",
            "job_scraper": true,
            "createdAt": "2022-05-27T22:45:03.246Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://boards.greenhouse.io/sothebys?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com",
            "company_website": "https://www.sothebys.com/en/",
            "industry": "Artists and Writers",
            "imagelink": "https://ucarecdn.com/c7df965e-2cc8-4de6-bd87-5afe16c6eacd/sotheby's-logo.png",
            "company_summary": "The world's premier destination for art and luxury.",
            "company_description": "Established in 1744, Sotheby's is the world's premier destination for art and luxury. Synonymous with innovation, Sotheby's promotes access, connoisseurship and preservation of fine art and rare objects through auctions, private sales and retail locations. \n  Our trusted global marketplace is supported by a network of specialists spanning 40 countries and 50 categories, which include Contemporary Art, Modern and Impressionist Art, Old Masters, Chinese Works of Art, Jewelry, Watches, Wine and Spirits, and Interiors, among many others.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "$150 each month toward employee's repayment of the principal amount of the debt, up to $1,800 per year.",
            "link_to_benefit_details": "https://www.benefitnews.com/news/sotheby-adds-student-loan-benefit"
        },
        {
            "uuid": "f59aaba1-0b0b-464c-b6b2-5c9e159f1725",
            "company_name": "Staples",
            "job_scraper": true,
            "createdAt": "2022-06-29T04:17:40.703Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://careers.staples.com/global/en?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com",
            "company_website": "staples.com",
            "industry": "Retail Office Equipment",
            "imagelink": "https://ucarecdn.com/e9f676ae-2eec-4e78-acff-1018a6174aa4/staples.png",
            "company_summary": "Whether you know exactly what you need, or you're looking for tools and inspiration to hit your goals, Staples is here for you.",
            "company_description": "Staples is The Worklife Fulfillment Company, helping businesses of all sizes be more productive, connected and inspired - however and wherever they work today. With dedicated account teams, category professionals, innovative brands and a curated product assortment for business, Staples provides customized solutions to help organizations achieve their goals. The company operates in North America through eCommerce and direct sales, and is headquartered near Boston, Massachusetts.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "Eligible employees - active, full-time U.S. associates with at least one outstanding loan obligation, who have obtained or are in the process of receiving a degree from an accredited institution will have their loan principal paid at $100 per month for 36 months.",
            "link_to_benefit_details": "https://www.benefitnews.com/news/staples-implements-student-loan-benefit"
        },
        {
            "uuid": "53e89fea-cbad-4c33-826e-bcd65a3ddba0",
            "company_name": "Teachable",
            "job_scraper": true,
            "createdAt": "2022-05-27T22:45:03.246Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://teachable.com/careers#job-list?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com",
            "company_website": "https://teachable.com/",
            "industry": "Internet",
            "imagelink": "https://ucarecdn.com/6d5911a9-cd9b-4f65-a590-c8decebc3b17/teachable.png",
            "company_summary": "We're helping you change the world by giving you the tools to share your knowledge through online courses and coaching.",
            "company_description": "Teachable builds products that transform experience and know-how into thriving businesses. We believe shared knowledge has the power to change lives, and by enabling people to share what they know, we create a better world together. \n  Our reach is proven: As of 2020, more than 37 million students have enrolled in courses created on Teachable, and instructors using our platform have collectively earned nearly $1 billion.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "Supplemental student loan repayment.",
            "link_to_benefit_details": "https://teachable.com/careers"
        },
        {
            "uuid": "e5d27eb4-9527-432d-a4d0-8ea2cfedfeaa",
            "company_name": "Terminix",
            "job_scraper": true,
            "createdAt": "2022-05-27T22:45:03.246Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://terminix.jobs.net/en-US/search?%3Futm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com",
            "company_website": "https://www.terminix.com/",
            "industry": "Consumer Services",
            "imagelink": "https://ucarecdn.com/91f15130-556b-4716-afb2-f1db9612ffd6/terminix.png",
            "company_summary": "Don't be bugged by your student loans.",
            "company_description": "Terminix is a leading provider of residential and commercial pest control. Terminix provides pest management services and protection against termites, mosquitoes, rodents, and other pests threatening human health and safety.\n  Headquartered in Memphis, Tenn., Terminix serves approximately 2.9 million residential and commercial customers in 24 countries and territories.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "Terminix has worked with Tuition.io to contribute $50 per month to those members of its 10,000 employee population in need of student debt relief.",
            "link_to_benefit_details": "https://www.benefitnews.com/news/terminix-employees-wont-be-bugged-by-student-loans-again"
        },
        {
            "uuid": "7c274fbf-cdc4-4b86-9446-56311c2b61af",
            "company_name": "The Goddard School",
            "job_scraper": true,
            "createdAt": "2022-06-29T04:17:40.703Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://recruiting.ultipro.com/GOD1001GOSY/JobBoard/d9bcba70-21be-405b-a68e-7fb1d8cb196c/?q=&o=postedDateDesc&w=&wc=&we=&wpst=",
            "company_website": "https://www.goddardschool.com/",
            "industry": "Education Administration Programs",
            "imagelink": "https://ucarecdn.com/f9d4eb51-2898-4e54-92bf-e0729ca3eb02/the-goddard-school.png",
            "company_summary": "The Goddard School offers the best childhood preparation for social and academic success.",
            "company_description": "The Goddard School uses the most current, academically endorsed methods to ensure that children have fun while learning the skills they need for long-term success in school and in life. Our talented teachers also collaborate with parents to nurture children into respectful, confident and joyful learners.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "The Goddard School will cover 20% of your monthly student loan payment, up to $100 per month. There's no lifetime cap, so you could potentially get help paying on your student loans for years.",
            "link_to_benefit_details": "https://joinjuno.com/financial-literacy/student-loans/25-companies-that-help-employees-pay-off-student-loans"
        },
        {
            "uuid": "36859470-a5ee-4ca6-9dbc-46235ccfbbfc",
            "company_name": "The U.S. Government",
            "job_scraper": true,
            "createdAt": "2022-06-29T04:17:40.703Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://www.usa.gov/government-jobs?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com",
            "company_website": "usa.gov",
            "industry": "Government Administration",
            "imagelink": "https://ucarecdn.com/bd9e7c99-c45e-40c5-aeae-45aa80870b33/logo-usagov.png",
            "company_summary": "The federal government of the United States (U.S. federal government) is the national government of the United States, a federal republic in North America, composed of 50 states, a federal district, five major self-governing territories and several island possessions.",
            "company_description": "The federal government is composed of three distinct branches: legislative, executive and judicial, whose powers are vested by the U.S. Constitution in the Congress, the president and the federal courts, respectively. The powers and duties of these branches are further defined by acts of Congress, including the creation of executive departments and courts inferior to the Supreme Court.\n  \n  The Federal student loan repayment program permits agencies to repay Federally insured student loans as a recruitment or retention incentive for candidates or current employees of the agency. The program implements 5 U.S.C. 5379, which authorizes agencies to set up their own student loan repayment programs to attract or retain highly qualified employees.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "Agencies may make payments to the loan holder of up to a maximum of $10,000 for an employee in a calendar year and a total of not more than $60,000 for any one employee.",
            "link_to_benefit_details": "https://www.opm.gov/policy-data-oversight/pay-leave/student-loan-repayment/"
        },
        {
            "uuid": "b6e0de73-354b-47c2-ae1e-b460395d39d2",
            "company_name": "UKG",
            "job_scraper": true,
            "createdAt": "2022-06-29T04:17:40.703Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://careers.ukg.com/?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com",
            "company_website": "https://www.kronos.com/",
            "industry": "Software Development",
            "imagelink": "https://ucarecdn.com/756e5fbc-49ee-45ca-af2a-c1c1324c2bb3/kronos.png",
            "company_summary": "Built from the merger of Ultimate Software & Kronos Inc, we are now UKG. We provide global HCM, payroll and workforce management solutions.",
            "company_description": "UKG is a leading provider of HR, payroll, and workforce management solutions for all people. But donâ€™t take our word for it: We are the only enterprise vendor ranked as a leader by all major analysts and peer review sites and have been recognized around the world for our workplace culture, innovative practices, and commitment to customer success.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "The company gives employees $500 a year to help them pay off their student loans.",
            "link_to_benefit_details": "https://www.wbur.org/news/2019/02/28/student-debt-relief-businesses"
        },
        {
            "uuid": "e2170d3b-e8b4-4380-8dd0-15d31c428f43",
            "company_name": "Unqork",
            "job_scraper": true,
            "createdAt": "2022-05-27T22:45:03.246Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://www.unqork.com/careers#openroles?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com",
            "company_website": "https://www.unqork.com/careers#openroles",
            "industry": "Software Development",
            "imagelink": "https://ucarecdn.com/99d8656e-4f62-4312-84b4-1699e4f11679/unqork.png",
            "company_summary": "At Unqork, we're changing the way companies create new products and software without having to write a single line of code.",
            "company_description": "Unqork is a no-code application platform that helps large enterprises build complex custom software faster, with higher quality, and lower costs than conventional approaches.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "Student loan payback program which is listed in each job posting. $1,000 per year.",
            "link_to_benefit_details": "https://www.unqork.com/careers#openroles"
        },
        {
            "uuid": "13dc7766-163f-49a5-8e60-3edb6a096377",
            "company_name": "Weedmaps",
            "job_scraper": true,
            "createdAt": "2022-05-27T22:45:03.246Z",
            "updatedAt": "2022-08-20T22:31:43.386Z",
            "company_jobpage": "https://weedmaps.com/careers?utm_source=dwindlestudentdebt.com&utm_medium=dwindlestudentdebt.com&utm_campaign=dwindlestudentdebt.com&ref=dwindlestudentdebt.com&source=dwindlestudentdebt.com",
            "company_website": "https://weedmaps.com/",
            "industry": "Internet",
            "imagelink": "https://ucarecdn.com/ca62f26b-931a-4206-bf0d-fccaacb97ddd/weedmaps.png",
            "company_summary": "Weedmaps is the technology platform powering the cannabis industry.",
            "company_description": "Founded in 2008, Weedmaps is a leading technology and software infrastructure provider to the cannabis industry. Our suite of cloud-based software and data solutions includes point of sale, logistics and ordering solutions that enable customers to scale their businesses while complying with the complex and disparate regulations applicable to the cannabis industry. \n  In addition, our platform provides consumers with information regarding cannabis products across web and mobile platforms, including listing local retailers and brands, facilitating product discovery and allowing consumers to educate themselves on cannabis and its history, uses and legal status.",
            "deletedAt": null,
            "benefit_type": "student_loan_repayment",
            "benefit_details": "Weedmaps will pay $1,000 per employee per year toward either a student loan or 529 savings plan, which will be paid in monthly installments of $83.33 per employee per month.",
            "link_to_benefit_details": "https://www.benefitnews.com/news/student-loan-benefit-provider-goodly-adds-weedmaps-to-list-of-employer-clients"
        }
    ]
}